"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

env = environ.Env()


def _parse_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    s = str(value).strip().lower()
    if s in ('1', 'true', 't', 'yes', 'y', 'on'):
        return True
    if s in ('0', 'false', 'f', 'no', 'n', 'off', ''):
        return False
    raise ValueError(f"Cannot parse {value!r} as a boolean")


def _parse_int(value, default=0):
    if value is None:
        return default
    try:
        return int(str(value).strip())
    except (ValueError, TypeError):
        return default


def _parse_list(value, default=None):
    if default is None:
        default = []
    if value is None:
        return list(default)
    if isinstance(value, (list, tuple)):
        result = []
        for item in value:
            s = str(item).strip()
            if s:
                result.append(s)
        return result if result else list(default)
    s = str(value).strip()
    if not s:
        return list(default)
    result = []
    for item in s.split(','):
        item = item.strip()
        if item:
            result.append(item)
    return result if result else list(default)


_INSECURE_SECRET_KEY_PREFIXES = (
    'django-insecure-',
    'change-me-to-a-long-random-string',
    'your-secret-key-here',
    'replace-me',
    'example-secret-key',
    'insecure',
)


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env('SECRET_KEY', default="django-insecure-*y(bpj*0ho*d6w9_cz0fvf428$&&jyzw==ztb$0(fkbvq)o-r5")

DEBUG = _parse_bool(env('DEBUG', default='0'))

ALLOWED_HOSTS = _parse_list(env('DJANGO_ALLOWED_HOSTS', default=''))

CSRF_TRUSTED_ORIGINS = _parse_list(env('DJANGO_CSRF_TRUSTED_ORIGINS', default=''))


if not DEBUG:
    key_lower = SECRET_KEY.lower()
    is_insecure = False
    if len(SECRET_KEY) < 50:
        is_insecure = True
    if key_lower.startswith('django-insecure-'):
        is_insecure = True
    for placeholder in _INSECURE_SECRET_KEY_PREFIXES:
        if placeholder in key_lower:
            is_insecure = True
            break
    unique_chars = len(set(SECRET_KEY))
    if unique_chars < 5:
        is_insecure = True
    if is_insecure:
        raise ImproperlyConfigured(
            "SECRET_KEY is not safe for production. "
            "It must be at least 50 characters long, contain at least 5 unique characters, "
            "and must not start with 'django-insecure-' or use a known placeholder "
            "(e.g. 'change-me-to-a-long-random-string'). "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(64))\""
        )


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


DATABASES = {
    'default': env.db(default='sqlite:///db.sqlite3'),
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

if not DEBUG:
    SECURE_SSL_REDIRECT = _parse_bool(
        env('DJANGO_SECURE_SSL_REDIRECT', default='1')
    )
    SECURE_HSTS_SECONDS = _parse_int(
        env('DJANGO_SECURE_HSTS_SECONDS', default='31536000')
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _parse_bool(
        env('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default='1')
    )
    SECURE_HSTS_PRELOAD = _parse_bool(
        env('DJANGO_SECURE_HSTS_PRELOAD', default='1')
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
